[tool.poetry]
name = "twitch-emulator"
version = "0.1.0"
description = ""
authors = ["Matthew Endicott <112583934+Matthew-Endicott-GR@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
irc = "^20.4.0"
pyautogui = "^0.9.54"
pygetwindow = "^0.0.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
